### ISSUE TITLE
StackOverflow Teams

### ISSUE THREAD

**Issue by Scene-n-Heard** [thePeras/copy-code-extension#3]
Hi,
Since SO have made changes to their private teams infrastructure, this plugin no longer works. Could you please add https://stackoverflowteams.com to the list.

Thanks

**Comment by thePeras** [comment]
Thanks very much for your contribution!

I added the stackoverflowteams domain to the extension and uploaded a new version.
Already online in Firefox, in review process at Google Chrome.
